name: metadata_god

repository: https://github.com/KRTirtho/metadata_god

packages:
  - packages/**

scripts:
  analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  version:
    description: Updates version numbers in all build files
    run: bash scripts/version.sh

  build:
    run: melos run build:apple && melos run build:android && melos run build:other
    description: Build all native libraries for the project.

  build:apple:
    run: bash scripts/build-apple.sh
    description: Build the XCFramework for iOS and macOS.

  build:android:
    run: bash scripts/build-android.sh
    description: Build the .tar.gz for Android.

  build:other:
    run: bash scripts/build-other.sh
    description: Build the .tar.gz for all other platforms.

  copylib:linux:
    run: |
      CURR_VERSION=metadata_god-v`awk '/^version: /{print $2}' packages/metadata_god/pubspec.yaml`
      cp platform-build/other.tar.gz packages/flutter_metadata_god/linux/$CURR_VERSION.tar.gz

  copylib:windows:
    run: |
      CURR_VERSION=metadata_god-v`awk '/^version: /{print $2}' packages/metadata_god/pubspec.yaml`
      cp platform-build/other.tar.gz packages/flutter_metadata_god/windows/$CURR_VERSION.tar.gz

  copylib:macos:
    run: |
      CURR_VERSION=metadata_god-v`awk '/^version: /{print $2}' packages/metadata_god/pubspec.yaml`
      cp platform-build/MetadataGod.xcframework.zip packages/flutter_metadata_god/macos/Frameworks/$CURR_VERSION.zip

  copylib:ios:
    run: |
      CURR_VERSION=metadata_god-v`awk '/^version: /{print $2}' packages/metadata_god/pubspec.yaml`
      cp platform-build/MetadataGod.xcframework.zip packages/flutter_metadata_god/ios/Frameworks/$CURR_VERSION.zip

  copylib:android:
    run: |
      CURR_VERSION=metadata_god-v`awk '/^version: /{print $2}' packages/metadata_god/pubspec.yaml`
      cp platform-build/android.tar.gz packages/flutter_metadata_god/android/$CURR_VERSION.tar.gz

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
